### PR TITLE
GRML_SMALL: apply same groups as in GRML_FULL

### PR DESCRIPTION
**Pull request by zeha**
No changes to the software set, just introduce the same groups as in the GRML_FULL set.

### CODE REVIEW

**Comment by jkirk** [comment]
Ad 6aad1b75a6) Why will reiserfsprogs be removed from Debian/trixie? (https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=reiserfsprogs;dist=unstable + https://tracker.debian.org/pkg/reiserfsprogs give me hints).

**Comment by jkirk** [comment]
JFTR: This PR consists of two commits: [6aad1b7](https://github.com/grml/grml-live/pull/179/commits/6aad1b75a6d8614871b2a876135de7e265cd1508) + [7c638f1](https://github.com/grml/grml-live/pull/179/commits/7c638f1499b986b0cf9e41c5e601c15147cdeeba). I think, only [7c638f1](https://github.com/grml/grml-live/pull/179/commits/7c638f1499b986b0cf9e41c5e601c15147cdeeba) should be in this one. 6aad1b7 belongs to #177.

**Comment by zeha** [comment]
> JFTR: This PR consists of two commits: [6aad1b7](https://github.com/grml/grml-live/pull/179/commits/6aad1b75a6d8614871b2a876135de7e265cd1508) + [7c638f1](https://github.com/grml/grml-live/pull/179/commits/7c638f1499b986b0cf9e41c5e601c15147cdeeba). I think, only [7c638f1](https://github.com/grml/grml-live/pull/179/commits/7c638f1499b986b0cf9e41c5e601c15147cdeeba) should be in this one. [6aad1b7](https://github.com/grml/grml-live/commit/6aad1b75a6d8614871b2a876135de7e265cd1508) belongs to #177.

Ah yes. This problem will solve itself once #177 is merged.

**Review by mika — APPROVED** [review]

**Comment by zeha** [comment]
(Retitled commit to add `SW:` in front)

**Pull request merged**
